### ISSUE TITLE
[PPG BETA 1.23] Mod won't compile

### ISSUE THREAD

**Issue by MellonMunch** [Cheeteau/PPG-Mod-Creator#2]
**Describe the bug** bug is.
its hard to say but the mod wont compile i renstalled the mod
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/94267852/158857897-686e6457-2ec1-4020-ac91-99e2eff36454.png)

**Desktop (please complete the following information):**
 - OS: windows 
 -  - Browser opra gx
 - Version 10

**Smartphone (please complete the following information):** 

**Additional context**
it started happening in the new 23 beta thanks -mellonmunch

**Comment by Cheeteau** [comment]
Just send the .wip of your mod folder

**Comment by MellonMunch** [comment]
Wip?  Sent from Mail for Windows From: CheetoSent: Friday, March 18, 2022 11:09 PMTo: Cheeteau/PPG-Mod-CreatorCc: MellonMunch; AuthorSubject: Re: [Cheeteau/PPG-Mod-Creator] [PPG BETA 1.23] Mod won't compile (Issue #2) Just send the .wip of your mod folder—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Cheeteau** [comment]
The .zip* of your mod, it would be easier for me to check where the issue comes from

**Comment by MellonMunch** [comment]
Sent from Mail for Windows From: CheetoSent: Saturday, March 19, 2022 10:42 AMTo: Cheeteau/PPG-Mod-CreatorCc: MellonMunch; AuthorSubject: Re: [Cheeteau/PPG-Mod-Creator] [PPG BETA 1.23] Mod won't compile (Issue #2) The .zip* of your mod, it would be easier for me to check where the issue comes from— Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Cheeteau** [comment]
Hi again, try to comment on the github.com website, it will be easier for the file transfer, as you will just drag and drop the zip file of your mod, and it will also be easier to read you!
When you reply with your email, it looks like this and it is kinda hard to understand!
![image](https://user-images.githubusercontent.com/29103374/159166198-37681763-8d52-4b89-96f8-c025a4dc1a1e.png)
