### ISSUE TITLE
I can't make any new elements

### ISSUE THREAD

**Issue by TheJamesCoder** [Cheeteau/PPG-Mod-Creator#5]
**Describe the bug**
Whenever I try to make a new element, there is a pop-up that says, "The name "test entity" is already used by another of your mod elements. Please use a different name." but when I check my already made elements there is no "test entity" in the elements.

**To Reproduce**
1. Go to Create Elements.
2. Fill in everything.
3. Make the object spawn sound a bit long.
4. See error.
5. You can't make anymore elements.

**Expected behavior**
I expected it would save the element in the created elements but it didn't.

**Screenshots**
![we4rfd](https://user-images.githubusercontent.com/95508352/170135566-80845d8b-bf80-41f8-b6b4-81f2bae9c164.PNG)
![us3e](https://user-images.githubusercontent.com/95508352/170135468-7792c31e-65e3-4bfb-b46f-c5bbf0981ad4.PNG)
It shows that there already is a "test entity" but in the second picture there isn't .

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [21H2]

**Additional context**
I was making a poppy playtime mod and I tried to add a new element with sounds but now I can't add anymore elements.

**Comment by Davideblue1** [comment]
the same thing happend to me!

**Comment by Davideblue1** [comment]
Try to change the name of the files it should work!
