### ISSUE TITLE
sooo, i was trynna make a new mod, but sudently the error of the name was already in my mod elements, even though it wasnt created or anything, no matter what i do, it will still show the same message, i have tried on other elements, and still the same thing.. is this a common error or did i do something wrong there?

### ISSUE THREAD

**Issue by Tuctom** [Cheeteau/PPG-Mod-Creator#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Davideblue1** [comment]
i figured it out if you use the same file of a mod for example you deleted an mod whit a thumb of a banana you try to create a banana whit the same thumb so i suggest you to change name of the files
