### ISSUE TITLE
Add vehicles

### ISSUE THREAD

**Issue by TheCoderLicer** [Cheeteau/PPG-Mod-Creator#9]
**Is your feature request related to a problem? Please describe.**
I was trying to make a mod that adds more vehicles, but there isn't a tutorial anywhere, nor a button here for a vehicle

**Describe the solution you'd like**
You click on the element type click vehicle put in the image(s) as well as the text and then save element.

**Describe alternatives you've considered**
Being able to add customizable activations for elements.

**Comment by Cheeteau** [comment]
Unfortunately I'm not working on this project anymore, I don't have much time.
